import 'package:flutter/material.dart';
import 'Color.dart';
import 'Style_icon.dart';

final ThemeData lightTheme = ThemeData(
    colorScheme: const ColorScheme(
      brightness: Brightness.light,
      primary: primary_Light,
      onPrimary: onPrimary_Light,
      primaryContainer: primaryContainer_Light,
      secondary: secondary_Light,
      onSecondary: onSecondary_Light,
      onSecondaryContainer: onSecondaryContainer_Light,
      tertiary: tertiary_Light,
      error: error_Light,
      onError: onError_Light,
      background: background_Light,
      onBackground: onBackground_Light,
      surface: surface_Light,
      onSurface: onSurface_Light,
    ),
    primaryColor: primaryContainer_Light,
    textTheme: const TextTheme(
        displayLarge: bodyLarge,
        displayMedium: displayMedium,
        displaySmall: displaySmall,
        headlineLarge: headlineLarge,
        headlineMedium: headlineMedium,
        headlineSmall: headlineSmall,
        titleLarge: titleLarge,
        titleMedium: titleMedium,
        titleSmall: titleSmall,
        labelLarge: lableLarge,
        labelMedium: lableMedium,
        labelSmall: lableSmall,
        bodyLarge: bodyLarge,
        bodyMedium: bodyMedium,
        bodySmall: bodySmall));
final ThemeData darkTheme = ThemeData(
  colorScheme: const ColorScheme(
    brightness: Brightness.dark,
    primary: primary_Dark,
    onPrimary: onPrimary_Dark,
    primaryContainer: primaryContainer_Dark,
    secondary: secondary_Dark,
    onSecondary: onSecondary_Dark,
    onSecondaryContainer: onSecondaryContainer_Dark,
    error: error_Dark,
    onError: onError_Dark,
    background: background_Dark,
    onBackground: onBackground_Dark,
    surface: surface_Dark,
    onSurface: onSurface_Dark,
  ),
  textTheme: const TextTheme(
      displayLarge: bodyLarge,
      displayMedium: displayMedium,
      displaySmall: displaySmall,
      headlineLarge: headlineLarge,
      headlineMedium: headlineMedium,
      headlineSmall: headlineSmall,
      titleLarge: titleLarge,
      titleMedium: titleMedium,
      titleSmall: titleSmall,
      labelLarge: lableLarge,
      labelMedium: lableMedium,
      labelSmall: lableSmall,
      bodyLarge: bodyLarge,
      bodyMedium: bodyMedium,
      bodySmall: bodySmall),
);
