// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcqbld0q9_T5228h79ZcD3avU1JgjLqZQ',
    appId: '1:781354384921:android:5bb835f45416602318b488',
    messagingSenderId: '781354384921',
    projectId: 'queezerapp',
    databaseURL: 'https://queezerapp-default-rtdb.firebaseio.com',
    storageBucket: 'queezerapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_Uwin1_zFYH-xYqjH1W545kXhaHHKb3E',
    appId: '1:781354384921:ios:ddc6b5a6d3ae617f18b488',
    messagingSenderId: '781354384921',
    projectId: 'queezerapp',
    databaseURL: 'https://queezerapp-default-rtdb.firebaseio.com',
    storageBucket: 'queezerapp.appspot.com',
    iosClientId: '781354384921-m3pvga8ujiare4ndq3si87edkqo8h4ua.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizapp',
  );
}
